server:
  port: 9094

spring:
  application:
    name: ORDER-SERVICE
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydb
      repository:
        enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/